server:
  port: 8081
spring:
  application:
    name: ms-users
  datasource:
    url: jdbc:mysql://{HOST DE AWS}:{PUERTO DE AWS}/{DB DE AWS}
    username: {USUARIO DE AWS}
    password: {CONTRASEÑA DE AWS}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
  sql:
    init:
      mode: always