server:
  port: 8081
spring:
  application:
    name: ms-users
  datasource:
    url: jdbc:mysql://localhost:3307/wallet_db
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
  sql:
    init:
      mode: always